sonar.projectKey=ronaldocf1721_full-cycle-ci
sonar.organization=ronaldocf1721

sonar.sources=.
sonar.exclusions=**

sonar.tests=.
sonar.tests.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out